export const CONSTANTS = {
  ADD_ADDRESS_MODAL_CONTENT: 'Congratulations! A new address has been created. Please click *Go to ' +
      'address management*, if you would like. Otherwise, click *Close* to close dialog and reset all fields in form.',
  ADD_ADDRESS_MODAL_TITLE: 'Message',
  ADD_NEW_ADDRESS: 'Add new Address',
  ADDRESS: 'Address',
  ADDRESS_MANAGER: 'ADDRESS MANAGER',
  ADDRESS_FORM_ID: 'form-address',
  ADDRESSES: 'addresses',
  CITY: 'City',
  COUNTRY: 'Country',
  CREATE: 'Create',
  CREATE_CAPTION: 'Please enter required fields(*) as below to create a new address. Please note that some of required fields, that depend on an entered field.',
  CREATE_FAILED: 'There was an error in creating a new address. Please try again',
  CREATE_NEW: 'Create New',
  CREATE_SUCCESS: 'A new address has been successfully created',
  CREATING: 'Creating...',
  DEFAULT_CENTER_LAT: 10.7775851,
  DEFAULT_CENTER_LNG: 106.6996137,
  DISTRICT: 'District',
  EDIT: 'Edit',
  EDIT_ADDRESS_MODAL_CONTENT: 'An address has been successfully saved. Please click *Go to ' +
      'address management*, if you would like. Otherwise, click *Close* to close dialog.',
  EDIT_ADDRESS_MODAL_TITLE: 'Message',
  EMPTY_ADDRESS: 'No address found. Please create a new one at *Create New Address* link.',
  EXPORT_TO_CSV: 'Export to CSV',
  FETCHING_ADDRESS: 'Fetching Address...',
  FIELD_CITY_NAME: 'city',
  FIELD_COUNTRY_NAME: 'country',
  FIELD_DISTRICT_NAME: 'district',
  FIELD_METHOD_TYPE_NAME: 'methodType',
  FIELD_STREET_NAME: 'streetName',
  FIELD_WARD_NAME: 'ward',
  GEOLOCATION_FAILED: 'Oops! The Geolocation service failed',
  GO_TO_ADDRESS_MANAGEMENT: 'Go to address management',
  GOOGLE_MAP_GEOCODE_URL: 'https://maps.googleapis.com/maps/api/geocode/json?latlng={0},{1}&key=AIzaSyCbXDLdyUijaa3DAl0vggy-Ve6mob1M4T8',
  HOME: 'Home',
  HOME_DESC1: 'Basically, this application enables you to manage information about addresses.',
  HOME_DESC21: 'If it interests you, please click',
  HOME_DESC22: 'here',
  HOME_DESC23: 'to go to manage address page',
  LOADING_DATA: 'Loading data...',
  LOADING_MAP: 'Loading Map...',
  MANAGE_ADDRESS: 'Manage Address',
  METHOD_TYPE: 'Method Type',
  METHOD_TYPE_MAP: 'Map',
  METHOD_TYPE_MAP_VALUE: '2',
  METHOD_TYPE_NORMAL: 'Normal',
  METHOD_TYPE_NORMAL_VALUE: '1',
  MODE_ADD: 'add',
  MODE_EDIT: 'edit',
  NOT_SUPPORTED_GEOLOCATION: 'Your browser does not support geolocation.',
  RESET: 'Reset',
  SAVE: 'Save',
  SAVING: 'Saving...',
  STREET_NAME: 'Street Name',
  TMPL_REQUIRED: '{0} is required!',
  VERSION_ADDRESS_APP: 'Version: 1.0.0.',
  WARD: 'Ward',
  WELCOME_ADDRESS_APP: 'Welcome you to address management!',
  YOUR_CURRENT_LOCATION: 'Your current location.'
};
